* GRASP: The GRAphical Scheme Programming

This is the repository of the GRASP project, which
is intended to be an extensible editor of s-expressions
optimized for interacting via touch screen.

The work is still in progress, and it has been divided
into stages. 

The most mature build of the prototype for Android
is probably the one from [[https://github.com/panicz/grasp-android/raw/b0a2a0875810d0b03aae076370db62d9f4e5e08e/stages/stage6/org.scheme.GRASP.apk][September 30, 2021)]]

A brief overview of the current capabilities of GRASP were
presented in [[https://www.youtube.com/watch?v=FlOghAlCDA4][this lightning talk from 2021 Scheme Workshop]].
However, the application shown in the presentation didn't yet
allow to evaluate expressions (so it corresponds to the stage 5 build).

Expression evaluation is briefly shown in [[https://www.youtube.com/shorts/oOHg74HYau4][this video]].

A full-blown demo in front of a live audience was also recorded
and is available [[https://www.youtube.com/watch?v=nGba4J-ThEk][here]], 
but it is in Polish, so it's unlikely that you'll find it useful
if you don't speak that language.

Currently the work mainly happens in the `stages/retreat/GRASP` directory.
It is a new prototype, written from the ground up in Kawa Scheme.
It doesn't work on Android yet - currently it can only be run in a terminal
(it uses a Java curses-like library called "lanterna" - a `.jar` is in
included the repo).

But the plan is to support both Android and terminals, and also build
a graphical client for the desktop.
